# Automatically generated by "pub global run bazel:bazelify".
load("@io_bazel_rules_dart//dart/build_rules:core.bzl", "dart_library")
load("@io_bazel_rules_dart//dart/build_rules:vm.bzl", "dart_vm_test")
load("@io_bazel_rules_webtesting//web:web.bzl", "web_test_suite")

package(default_visibility = ["//visibility:public"])

dart_library(
    name = "webdriver",
    srcs = glob(["lib/**"]),
    pub_pkg_name = "webdriver",
    visibility = ["//visibility:public"],
    deps = [
        "@org_dartlang_pub_archive//:archive",
        "@org_dartlang_pub_matcher//:matcher",
        "@org_dartlang_pub_path//:path",
        "@org_dartlang_pub_stack_trace//:stack_trace",
        "@org_dartlang_pub_unittest//:unittest",
    ],
)

dart_vm_test(
    name = "io_test_wrapped",
    srcs = glob(
        ["test/**/*.dart"],
        exclude = ["**/html_*.dart"],
    ),
    data = glob(
        ["test/**"],
        exclude = ["**/*.dart"],
    ),
    script_file = "test/io_test.dart",
    tags = [
        "manual",
        "noci",
    ],
    deps = [
        ":webdriver",
        "@org_dartlang_pub_matcher//:matcher",
        "@org_dartlang_pub_path//:path",
        "@org_dartlang_pub_test//:test",
    ],
)

web_test_suite(
    name = "io_test",
    browsers = [
        "@io_bazel_rules_webtesting//browsers:firefox-native",
    ],
    local = True,
    test = ":io_test_wrapped",
)
