def webdriver_dart_repositories():
  native.new_http_archive(
      name="org_dartlang_pub_analyzer",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/analyzer-0.29.1.tar.gz",
      build_file="build_files/analyzer.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_archive",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/archive-1.0.27.tar.gz",
      build_file="build_files/archive.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_args",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/args-0.13.7.tar.gz",
      build_file="build_files/args.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_async",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/async-1.11.3.tar.gz",
      build_file="build_files/async.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_barback",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/barback-0.15.2+9.tar.gz",
      build_file="build_files/barback.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_boolean_selector",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/boolean_selector-1.0.2.tar.gz",
      build_file="build_files/boolean_selector.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_charcode",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/charcode-1.1.1.tar.gz",
      build_file="build_files/charcode.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_collection",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/collection-1.12.0.tar.gz",
      build_file="build_files/collection.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_convert",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/convert-2.0.1.tar.gz",
      build_file="build_files/convert.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_crypto",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/crypto-2.0.1.tar.gz",
      build_file="build_files/crypto.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_csslib",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/csslib-0.13.2+2.tar.gz",
      build_file="build_files/csslib.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_glob",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/glob-1.1.3.tar.gz",
      build_file="build_files/glob.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_html",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/html-0.13.1.tar.gz",
      build_file="build_files/html.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_http",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/http-0.11.3+9.tar.gz",
      build_file="build_files/http.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_http_multi_server",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/http_multi_server-2.0.3.tar.gz",
      build_file="build_files/http_multi_server.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_http_parser",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/http_parser-3.0.3.tar.gz",
      build_file="build_files/http_parser.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_isolate",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/isolate-0.2.3.tar.gz",
      build_file="build_files/isolate.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_logging",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/logging-0.11.3+1.tar.gz",
      build_file="build_files/logging.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_matcher",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/matcher-0.12.0+2.tar.gz",
      build_file="build_files/matcher.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_meta",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/meta-1.0.4.tar.gz",
      build_file="build_files/meta.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_mime",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/mime-0.9.3.tar.gz",
      build_file="build_files/mime.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_package_config",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/package_config-1.0.0.tar.gz",
      build_file="build_files/package_config.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_package_resolver",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/package_resolver-1.0.2.tar.gz",
      build_file="build_files/package_resolver.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_path",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/path-1.4.0.tar.gz",
      build_file="build_files/path.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_plugin",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/plugin-0.2.0.tar.gz",
      build_file="build_files/plugin.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_pool",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/pool-1.2.4.tar.gz",
      build_file="build_files/pool.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_pub_semver",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/pub_semver-1.3.2.tar.gz",
      build_file="build_files/pub_semver.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_shelf",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/shelf-0.6.7+1.tar.gz",
      build_file="build_files/shelf.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_shelf_packages_handler",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/shelf_packages_handler-1.0.0.tar.gz",
      build_file="build_files/shelf_packages_handler.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_shelf_static",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/shelf_static-0.2.4.tar.gz",
      build_file="build_files/shelf_static.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_shelf_web_socket",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/shelf_web_socket-0.2.1.tar.gz",
      build_file="build_files/shelf_web_socket.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_source_map_stack_trace",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/source_map_stack_trace-1.1.3.tar.gz",
      build_file="build_files/source_map_stack_trace.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_source_maps",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/source_maps-0.10.1+2.tar.gz",
      build_file="build_files/source_maps.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_source_span",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/source_span-1.3.0.tar.gz",
      build_file="build_files/source_span.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_stack_trace",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/stack_trace-1.7.0.tar.gz",
      build_file="build_files/stack_trace.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_stream_channel",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/stream_channel-1.5.0.tar.gz",
      build_file="build_files/stream_channel.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_string_scanner",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/string_scanner-1.0.1.tar.gz",
      build_file="build_files/string_scanner.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_test",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/test-0.12.17.tar.gz",
      build_file="build_files/test.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_typed_data",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/typed_data-1.1.3.tar.gz",
      build_file="build_files/typed_data.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_unittest",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/unittest-0.11.6+4.tar.gz",
      build_file="build_files/unittest.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_utf",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/utf-0.9.0+3.tar.gz",
      build_file="build_files/utf.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_watcher",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/watcher-0.9.7+3.tar.gz",
      build_file="build_files/watcher.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_web_socket_channel",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/web_socket_channel-1.0.4.tar.gz",
      build_file="build_files/web_socket_channel.BUILD")
  native.new_http_archive(
      name="org_dartlang_pub_yaml",
      url="https://storage.googleapis.com/pub.dartlang.org/packages/yaml-2.1.12.tar.gz",
      build_file="build_files/yaml.BUILD")
