# Automatically generated by "pub global run bazel:bazelify".
# DO NOT MODIFY BY HAND

# Bazelify: 1 libraries.
load("@io_bazel_rules_dart//dart/build_rules:core.bzl", "dart_library")

package(default_visibility = ["//visibility:public"])

_PUB_DEPS = [
    "@org_dartlang_pub_analyzer//:analyzer",
    "@org_dartlang_pub_args//:args",
    "@org_dartlang_pub_async//:async",
    "@org_dartlang_pub_barback//:barback",
    "@org_dartlang_pub_boolean_selector//:boolean_selector",
    "@org_dartlang_pub_collection//:collection",
    "@org_dartlang_pub_glob//:glob",
    "@org_dartlang_pub_http_multi_server//:http_multi_server",
    "@org_dartlang_pub_matcher//:matcher",
    "@org_dartlang_pub_package_resolver//:package_resolver",
    "@org_dartlang_pub_path//:path",
    "@org_dartlang_pub_pool//:pool",
    "@org_dartlang_pub_pub_semver//:pub_semver",
    "@org_dartlang_pub_shelf//:shelf",
    "@org_dartlang_pub_shelf_packages_handler//:shelf_packages_handler",
    "@org_dartlang_pub_shelf_static//:shelf_static",
    "@org_dartlang_pub_shelf_web_socket//:shelf_web_socket",
    "@org_dartlang_pub_source_map_stack_trace//:source_map_stack_trace",
    "@org_dartlang_pub_source_maps//:source_maps",
    "@org_dartlang_pub_source_span//:source_span",
    "@org_dartlang_pub_stack_trace//:stack_trace",
    "@org_dartlang_pub_stream_channel//:stream_channel",
    "@org_dartlang_pub_string_scanner//:string_scanner",
    "@org_dartlang_pub_web_socket_channel//:web_socket_channel",
    "@org_dartlang_pub_yaml//:yaml",
]

# Generated automatically for package:test
dart_library(
    name = "test",
    srcs = glob(["lib/**"]),
    pub_pkg_name = "test",
    deps = _PUB_DEPS,
)
