name: Comment on PRs

on:
  # Trigger this workflow after the Publish workflow completes. This workflow
  # will have permissions to create comments on the PR, even if the original
  # workflow couldn't.
  workflow_run:
    workflows: 
      - Publish
    types:
      - completed

jobs:
  upload:
    uses: dart-lang/ecosystem/.github/workflows/post_summaries.yaml@main
    permissions:
      pull-requests: write
